version: "3.8"
services:
  jeager:
    image:  jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    volumes:
      - "./jaeger/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    ports:
      - 16686:16686 # UI
      - 4317:4317 # gRPC incoming
      - 4318:4318 # HTTP incoming
      - 14268:14268 # export to prometheus
      - 14250:14250 # export to prometheus

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml --no-scrape.adjust-timestamps
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extensions
      - "8888:8888"   # prometheus metrics exposed by the collector
      - "8889:8889"   # prometheus exporter metrics
      - "13133:13133" # heath
      - "4320:4320"   # OTLP gRPC
      - "4319:4319"   # OTLP HTTP
      - "55670:55679" # zapges
    depends_on:
      - jeager