version: "3.8"
services:
  jeager:
    image:  jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=prometheus:9090
    ports:
      - 5775:5775/udp # accept zipkin.thrift over compact thrift protocol
      - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
      - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
      - 5778:5778     # serve configs
      - 16686:16686   # serve frontend
      - 14268:14268  	# accept jaeger.thrift directly from clients
      - 9411:9411     # Zipkin compatible endpoint
      - 14250:14250   # jaeger imports


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  

  collector:
    #image: otel/opentelemetry-collector:latest
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "1888:1888"   # pprof extensions
      - "8888:8888"   # prometheus metrics exposed by the collector
      - "8889:8889"   # prometheus exporter metrics
      - "13133:13133" # heath
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "55670:55679" # zapges
    depends_on:
      - jeager