receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4319
      http:
        endpoint: 0.0.0.0:4320

connectors:
  spanmetrics:
    namespace: span.metrics


exporters:
  prometheusremotewrite:
    endpoint: prometheus:9090/api/v1/write
    target_info:
      enabled: true

  logging:
    loglevel: debug

  otlp:
    endpoint: "jeager:4317"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging, otlp, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: []
      exporters: [logging, prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]